name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version-file: '.java-version'
          cache: 'maven'

      - name: Run tests with Testcontainers
        run: mvn clean verify

      - name: Test Docker Image Build
        run: |
          set +e
          docker build --no-cache --tag trade-demo-backend .
          exit $?

#      - name: SonarCloud Scan
#        if: github.actor != 'dependabot[bot]'
#        uses: SonarSource/sonarqube-scan-action@v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
